#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/Wentao/Desktop/3110/final-project/cs3110-Final-Project

rm -f src/game_models/maps.cmi
rm -f src/game_models/maps.cmo
rm -f src/game_models/player.cmi
rm -f src/game_models/player.cmo
# Also clean the script itself
rm -f /mnt/c/Users/Wentao/Desktop/3110/final-project/cs3110-Final-Project/_build/sanitize.sh
